site_name: OpenUtau
site_url: https://nagotown.github.io
repo_url: https://github.com/nagotown/openutau.com

edit_uri: edit/zensical/docs/

# repo_name: openutau/openutau

nav:
  - index.md
  - User Guide:
    - wiki/index.md
    - For beginners:
      - wiki/Tutorials.md
      - wiki/Install.md
      - wiki/Getting-Started.md
      - wiki/FAQ.md
      - wiki/Keyboard-Shortcuts.md
    - Basics:
      - wiki/Phonemizers.md
      - wiki/Resamplers-and-Wavtools.md
      - wiki/Expressions-(Flags).md
      - wiki/Legacy-Plugins.md
    - Advanced:
      - wiki/Voicebank-development.md
      - wiki/ENUNU-NNSVS-Support.md
      - wiki/DiffSinger-support.md
      - wiki/VOICEVOX-support.md
      - wiki/Singer-Settings-and-Requirements.md
  - Developer Guide:
    - Compilation:
      - dev/Compiling-from-source.md
      - dev/Compiling-G2p-Models.md
    - Development:
      - dev/Developing-new-phonemizers.md
      - dev/Adding-support-for-a-new-synthesis-engine.md
      - dev/Fork-OpenUtau-and-develop-a-new-editor.md
    - Other:
      - dev/USTX-file-format.md
      - dev/Contributing-to-OpenUtau's-localization.md
      - dev/tech-note-‐-music-is-music,-phonetics-is-phonetics-(also-why-you-don't-need-legacy-plugins).md
  - Reference:
    - reference/index.md
    - reference/Release-Notes.md
    - reference/Known-Bugs.md

theme:
  name: material
  favicon: assets/images/openutau.png
  logo: assets/images/openutau.png
  icon:
    repo: fontawesome/brands/github
  # custom_dir: overrides
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - content.action.edit
    - content.action.view

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - ezlinks
  - gh-admonitions
  # - redirects:
  #     redirect_maps:
  #       'index.md': 'OpenUtau.wiki/Home.md'

extra:
  alternate:
    - name: 日本語
      link: https://w.atwiki.jp/openutau_ja/pages/1.html
      lang: ja

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde